import maplibregl, { type Map as MlMap } from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
import { forwardRef, useEffect, useImperativeHandle, useRef } from 'react';
import { CITIZEN_REPORT_POINTS, NER_BOUNDS, RISK_GRID, STATE_BOUNDS } from '../../mocks/riskGrid';
import { RISK_LEVEL_HEX } from '../../utils/risk';
import { useDashboardStore } from '../../store/dashboardStore';

export interface RiskMapHandle {
  zoomIn: () => void;
  zoomOut: () => void;
  resetNorth: () => void;
}

interface RiskMapProps {
  height: number;
  coarse?: boolean;
}

/**
 * Thin MapLibre GL wrapper standing in for the design's synthetic "ner-risk-map"
 * component. Uses CARTO's free Positron basemap (no key required). Renders the
 * mock risk grid + citizen report points (src/mocks/riskGrid.ts) on the RISK
 * layer, and the real GSI landslide inventory (public/data/landslide_heatmap.geojson,
 * generated by scripts/build-landslide-heatmap.mjs) as a heatmap on the
 * INVENTORY layer.
 */
const RiskMap = forwardRef<RiskMapHandle, RiskMapProps>(function RiskMap({ height, coarse }, ref) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const mapRef = useRef<MlMap | null>(null);
  const selectedCellId = useDashboardStore((s) => s.selectedCellId);
  const selectZone = useDashboardStore((s) => s.selectZone);
  const selectedState = useDashboardStore((s) => s.selectedState);
  const activeMapLayer = useDashboardStore((s) => s.activeMapLayer);
  const isFirstStateChange = useRef(true);

  useImperativeHandle(ref, () => ({
    zoomIn: () => mapRef.current?.zoomIn(),
    zoomOut: () => mapRef.current?.zoomOut(),
    resetNorth: () => mapRef.current?.easeTo({ bearing: 0, pitch: 0 }),
  }));

  useEffect(() => {
    if (!containerRef.current || mapRef.current) return;

    const map = new maplibregl.Map({
      container: containerRef.current,
      style: 'https://basemaps.cartocdn.com/gl/positron-gl-style/style.json',
      bounds: NER_BOUNDS,
      fitBoundsOptions: { padding: 24 },
      attributionControl: false,
    });
    mapRef.current = map;

    map.on('load', () => {
      map.addSource('risk-grid', { type: 'geojson', data: RISK_GRID as any });
      map.addLayer({
        id: 'risk-grid-fill',
        type: 'fill',
        source: 'risk-grid',
        layout: { visibility: activeMapLayer === 'RISK' ? 'visible' : 'none' },
        paint: {
          'fill-color': [
            'match',
            ['get', 'risk_level'],
            'CRITICAL', RISK_LEVEL_HEX.CRITICAL,
            'HIGH', RISK_LEVEL_HEX.HIGH,
            'MODERATE', RISK_LEVEL_HEX.MODERATE,
            'LOW', RISK_LEVEL_HEX.LOW,
            'VERY_LOW', RISK_LEVEL_HEX.VERY_LOW,
            '#8A8F88',
          ],
          'fill-opacity': 0.75,
        },
      });
      map.addLayer({
        id: 'risk-grid-outline',
        type: 'line',
        source: 'risk-grid',
        layout: { visibility: activeMapLayer === 'RISK' ? 'visible' : 'none' },
        paint: { 'line-color': '#1B211D', 'line-width': 1 },
      });
      map.addSource('citizen-reports', { type: 'geojson', data: CITIZEN_REPORT_POINTS as any });
      map.addLayer({
        id: 'citizen-reports-points',
        type: 'circle',
        source: 'citizen-reports',
        paint: {
          'circle-radius': 5,
          'circle-color': '#FCFBF7',
          'circle-stroke-color': '#3E463F',
          'circle-stroke-width': 1.6,
        },
      });

      // Real GSI landslide inventory (820 events), weighted by a simulated intensity —
      // see scripts/build-landslide-heatmap.mjs for provenance and derivation.
      map.addSource('landslide-inventory', { type: 'geojson', data: '/data/landslide_heatmap.geojson' });
      map.addLayer({
        id: 'landslide-heat',
        type: 'heatmap',
        source: 'landslide-inventory',
        layout: { visibility: activeMapLayer === 'INVENTORY' ? 'visible' : 'none' },
        paint: {
          'heatmap-weight': ['interpolate', ['linear'], ['get', 'sim_intensity'], 0, 0, 1, 1],
          'heatmap-intensity': ['interpolate', ['linear'], ['zoom'], 4, 0.6, 9, 2.2],
          'heatmap-radius': ['interpolate', ['linear'], ['zoom'], 4, 8, 9, 26],
          'heatmap-opacity': ['interpolate', ['linear'], ['zoom'], 4, 0.9, 10, 0.35],
          'heatmap-color': [
            'interpolate',
            ['linear'],
            ['heatmap-density'],
            0, 'rgba(46,125,91,0)',
            0.2, RISK_LEVEL_HEX.VERY_LOW,
            0.4, RISK_LEVEL_HEX.LOW,
            0.6, RISK_LEVEL_HEX.MODERATE,
            0.8, RISK_LEVEL_HEX.HIGH,
            1, RISK_LEVEL_HEX.CRITICAL,
          ],
        },
      });
      map.addLayer({
        id: 'landslide-points',
        type: 'circle',
        source: 'landslide-inventory',
        layout: { visibility: activeMapLayer === 'INVENTORY' ? 'visible' : 'none' },
        paint: {
          'circle-radius': ['interpolate', ['linear'], ['zoom'], 6, 2, 12, 6],
          'circle-color': [
            'interpolate',
            ['linear'],
            ['get', 'sim_intensity'],
            0.15, RISK_LEVEL_HEX.VERY_LOW,
            0.4, RISK_LEVEL_HEX.MODERATE,
            0.7, RISK_LEVEL_HEX.HIGH,
            1, RISK_LEVEL_HEX.CRITICAL,
          ],
          'circle-stroke-color': '#FCFBF7',
          'circle-stroke-width': 1,
          'circle-opacity': ['interpolate', ['linear'], ['zoom'], 6, 0, 8, 1],
        },
      });

      const inventoryPopup = new maplibregl.Popup({ closeButton: false, closeOnClick: false });
      map.on('mousemove', 'landslide-points', (e) => {
        map.getCanvas().style.cursor = 'pointer';
        const f = e.features?.[0];
        if (!f || !e.lngLat) return;
        const p = f.properties as Record<string, unknown>;
        inventoryPopup
          .setLngLat(e.lngLat)
          .setHTML(
            `<div style="font-family: var(--font-mono, monospace); font-size: 11px; line-height: 1.5;">` +
              `<strong>${p.landslide_id}</strong> · ${p.source}<br/>` +
              `${p.district}, ${p.state}<br/>` +
              `Type: ${p.landslide_type ?? 'unrecorded'}<br/>` +
              `Sim. intensity: ${p.sim_intensity} <span style="color:#8A8F88">(simulated)</span>` +
              `</div>`,
          )
          .addTo(map);
      });
      map.on('mouseleave', 'landslide-points', () => {
        map.getCanvas().style.cursor = '';
        inventoryPopup.remove();
      });

      map.on('click', 'risk-grid-fill', (e) => {
        const cellId = e.features?.[0]?.properties?.cell_id;
        if (cellId) selectZone(cellId);
      });
      map.on('mouseenter', 'risk-grid-fill', () => {
        map.getCanvas().style.cursor = 'pointer';
      });
      map.on('mouseleave', 'risk-grid-fill', () => {
        map.getCanvas().style.cursor = '';
      });
    });

    return () => {
      map.remove();
      mapRef.current = null;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // outline the selected zone
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !map.isStyleLoaded() || !map.getLayer('risk-grid-outline')) return;
    map.setPaintProperty('risk-grid-outline', 'line-width', [
      'case',
      ['==', ['get', 'cell_id'], selectedCellId],
      3,
      1,
    ]);
    map.setPaintProperty('risk-grid-outline', 'line-color', [
      'case',
      ['==', ['get', 'cell_id'], selectedCellId],
      '#1B211D',
      '#3E463F',
    ]);
  }, [selectedCellId]);

  useEffect(() => {
    const map = mapRef.current;
    if (!map) return;
    map.resize();
  }, [height]);

  // Toggle which map layer is visible (RISK grid vs real landslide inventory heatmap).
  useEffect(() => {
    const map = mapRef.current;
    if (!map || !map.isStyleLoaded()) return;
    const riskVisible = activeMapLayer === 'RISK' ? 'visible' : 'none';
    const inventoryVisible = activeMapLayer === 'INVENTORY' ? 'visible' : 'none';
    if (map.getLayer('risk-grid-fill')) map.setLayoutProperty('risk-grid-fill', 'visibility', riskVisible);
    if (map.getLayer('risk-grid-outline')) map.setLayoutProperty('risk-grid-outline', 'visibility', riskVisible);
    if (map.getLayer('landslide-heat')) map.setLayoutProperty('landslide-heat', 'visibility', inventoryVisible);
    if (map.getLayer('landslide-points')) map.setLayoutProperty('landslide-points', 'visibility', inventoryVisible);
  }, [activeMapLayer]);

  // Fly to the selected state's bounds whenever it changes (initial mount keeps the full-NER view).
  useEffect(() => {
    if (isFirstStateChange.current) {
      isFirstStateChange.current = false;
      return;
    }
    const map = mapRef.current;
    if (!map) return;
    const bounds = selectedState === 'All States' ? NER_BOUNDS : STATE_BOUNDS[selectedState];
    if (bounds) map.fitBounds(bounds, { padding: 32, duration: 800 });
  }, [selectedState]);

  return <div ref={containerRef} style={{ width: '100%', height, background: coarse ? '#EEEBE3' : undefined }} />;
});

export default RiskMap;
